server:
  port: 8892
spring:
  application:
    name: starlink-res
  datasource:
    name: bms_res
    url: jdbc:mysql://172.30.9.21:3306/bms_res?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Star_Link2019_.123
  #    type: com.alibaba.druid.pool.DruidDataSource


system:
  ignore:
    response:
      advice: /download/**

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
    suffix-name: _imgSuf
    percent: 0.25
  tracker:
    addressList:
      - 172.30.9.26:22122
      - 172.30.9.27:22122
  web-server:
    url: http://172.30.9.26/
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    max-wait-millis: 155
obs:
  end-point: https://obs.cn-east-2.myhuaweicloud.com
  access-key: MTMDAN7TXAWZWLU6TRAS
  secret-key: V4Z1LKGjQXEsCV99VN7TM2sXMo34QnXEHHCXdXo1
oss:
  end-point: https://oss-cn-shenzhen.aliyuncs.com
  access-key: LTAI4Fg4W2QuJHDa93De41SE
  secret-key: Jo4vDrt63MgGx9S1Ek1XSkBBZzeSJk
cos:
  region : ap-guangzhou
  access-key: AKIDyrngZO1RGuNeFsKo5BXn7Yu9DNOHd8mJ
  secret-key: YBe8Zq386rX6bfZR9jwNfqIZf9oIajqq